import matplotlib.pyplot as plt
import pandas as pd

columns = ['Nr', 'Geb-Datum', 'Behandlungsbeginn', 'Behandlungsende', 'age',
           'sex F1__M2', 'n_total', 'n_rechts', 'n_links', 'n_bilateral',
           'n_bilateral_Lucentis', 'n_bilateral_Eylea',
           'n_bilateral_Lucentis_Eylea', 'n_unilateral', 'n_unilateral_Lucentis',
           'n_unilateral_Eylea', 'n_Lucentis_total', 'n_Eylea_total',
           'Ozurdex                       nein 0__ bds 1__  rechts 2__ links 3',
           'Argon Laserbehandelt      nein 0__ bds 1__  rechts 2__ links 3',
           'Cat_Surgery        nein 0__ bds 1__ rechts 2__ links 3',
           'Kapsulotomie            nein   0__ bds 1__  rechts 2__ links 3',
           'Oraya_SRT nein   0__ bds 1 __ rechts 2__ links 3',
           'Eyesurgery            keine 0 __ PPV mit Membranpeeling 1 __ Lidkorrektur (Ektropium) 2 __ Tumor Exzision Augenlid 3 __ Dacryocystorhinostomie 4 __ Exzision Fettprolaps subkonjunktival 5 __ TPP 6__ Laseriridotomie, SLT, TE 7__ Vordere Vitrektomie bei kompl. Cat-OP 8 __ EDTA Abrasio 9 __ Parazentese zum Druckausgleich 10__  BH-Naht nach FK 11',
           'Eysurgery_Treatmentside            keine 0 __ bds 1 __ rechts 2 __ links 3 ',
           'Surgery_other        keine 0 __ Diagnostische Eingriffe zB Herzkatheter 1 __ Kardiologische, Angiologische Eingriffe 2 __ Orthopädische Eingriffe 3 __ Onkologische Eingriffe 4__ Nierentransplantation 5 __ Dermatologische Eingriffe 6__ Gastro Eingriffe 7 __ Neurochirurgische Eingriffe 8 __ Zahnärztliche, Kieferchirurgische Eingriffe 9',
           'OP',
           'pretreated     (extern oder vor 01/11)          nein 0__ rechts 2__       links 3__       bds 1',
           'BCVA_baseline_R BCVA (ETDRS) letters \nBaseline R',
           'BCVA_baseline_L BCVA (ETDRS) letters \nBaseline L',
           'BCVA_endline_R BCVA (ETDRS) letters \nnach letzter IVI im Beobachtungszeitraum R',
           'BCVA_endline_L BCVA (ETDRS) letters \nnach letzter IVI im Beobachtungszeitraum L',
           'Hyposphagma_bilateral                  keine 0         __  Hyposphagma unilateral nicht antikoag. Lucentis 1 __ Hyposphagma unilateral antikoag. Lucentis 2 __ Hyposp. bilat nicht antiko. Luc 3 __Hyopsph. bilat. antiko. Luc 4 __ Hyposp. unilateral Nicht Antikoa. Eylea 5    __ Hyposphagma unilat antikoag. Eylea 6   __ Hyposph. bilat nicht antikoa. Eylea 7     __ Hyposphagma bilat antikoa. Eylea 8 __ Hyposphagma unilat nicht antik. E&L 9',
           'Sicca_bilateral    keine 0__ Sicca-Sy unilat Luc 1 __ Sicca Sy bilat Luc 2__ Sicca-Sy unilat Eylea 3__ Sicca Sy bilat Eylea 4__ Sicca-Sy unilat Luc/Eylea 5__ Sicca Sy bilat Luc/Eylea 6',
           'Allergy_bilateral keine 0 __ Allerg. Reaktion unilat Luc 1__ Allerg bilat Luc 2__ Allerg. Reaktion unilat Eylea 3 __ Allergie bilat Eylea 4',
           'Allergy_cause_bilateral  keine 0 __ Konservierungsmittel 1 __ Jod 2 __ Tobrex 3 __ Octenisept 4__ Desinfektionsmittel 5 __ unklar 6 __ Floxal SDU 7 __ Pollen 8',
           'IOD_bilateral keine 0 __ IOD Dekompensation Luc unilateral ohne vorb. Glaukom 1__ IOD Dekomp Luc unilateral mit Glaukom 2__ IOD Dekomp Luc bilateral ohne Glaukom 3__IOD Dekomp Luc bilat mit Glaukom 4__IOD Dekomp Eylea unilateral ohne Glaukom 5__IOD Dekomp Eylea unilateral mit Glaukom 6__IOD Dekomp Eylea bilat ohne Glaukom 7__IOD Dekomp Eylea bilat mit Glaukom 8',
           'Hyposphagma_unilateral               keine 0         __  Hyposphagma unilateral nicht antikoag. Lucentis 1 __ Hyposphagma unilateral antikoag. Lucentis 2 __ Hyposp. bilat nicht antiko. Luc 3 __Hyopsph. bilat. antiko. Luc 4 __ Hyposp. unilateral Nicht Antikoa. Eylea 5    __ Hyposphagma unilat antikoag. Eylea 6   __ Hyposph. bilat nicht antikoa. Eylea 7     __ Hyposphagma bilat antikoa. Eylea 8 __ Hyposphagma unilat nicht antik. E&L 9__ Hyposphagma unilat antikoaguliert E&L 10',
           'Sicca_unilateral   keine 0__ Sicca-Sy unilat Luc 1 __ Sicca Sy bilat Luc 2__ Sicca-Sy unilat Eylea 3__ Sicca Sy bilat Eylea 4__ Sicca-Sy unilat Luc/Eylea 5__ Sicca Sy bilat Luc/Eylea 6',
           'Allergy_unialteral keine 0 __ Allerg. Reaktion unilat Luc 1__ Allerg bilat Luc 2__ Allerg. Reaktion unilat Eylea 3 __ Allergie bilat Eylea 4',
           'Allergy_cause_unilateral keine 0 __ Konservierungsmittel 1 __ Jod 2 __ Tobrex 3 __ Octenisept 4 __ Desinfektionsmittel 5 __ unklar 6',
           'IOD_unialteral keine 0 __ IOD Dekompensation Luc unilateral ohne vorb. Glaukom 1__ IOD Dekomp Luc unilateral mit Glaukom 2__ IOD Dekomp Luc bilateral ohne Glaukom 3__IOD Dekomp Luc bilat mit Glaukom 4__IOD Dekomp Eylea unilateral ohne Glaukom 5__IOD Dekomp unilateral mit Glaukom 6__IOD Dekomp Eylea bilat ohne Glaukom 7__IOD Dekomp Eylea bilat mit Glaukom 8',
           'ocular_AE_bilateral           bilateral                   (Adverse event/Serious adverse event) Freitext   keine 0                      Lidprobleme 1 __ Mouches, GK Destruktion, ERF, HGA 2 __ VK oder GK Blutung 3 __ NH Foramen und Makulaschichtforamen 4 __ ZVV oder VAV unilateral 5 __ Charles bonnet 6  __ BH Pathologien 7 __ Uveitis anterior 8 __ HH Pathologien 9 __  Doppelbilder 10 __  Amotio rhetinae 11__ Endophthalmitis 12 __ AH Nävus 13 __  Erosio cornea, Ulcus cornea 14__ IOL dezentriert 15__ Augenmigräne 16 __ Iritis, Iridocyclitis, Irisdefekt 17 __ HKL subluxiert 18 ',
           'ocular_AE_bilateral_treatmentside             nicht betroffen 0_ bds 1 __   rechts 2 __  links 3',
           'ocular_AE_bilateral_medication    nicht betroffen 0_ bei Lucentis 1 __      bei Eylea 2 __       bei Luc & Eylea 3',
           'ocular_AE_bilateral_time   Time nach IVI till Event       nicht betroffen 0__   innert 24h 1 __ 24h-1 Woche 2 __ innerhalb 1Monat 3 __  >1Monat 4 __  unbekannt 5',
           'ocular_AE_unilateral      unilateral                   (Adverse event/Serious adverse event) Freitext                 keine 0                      Lidprobleme 1 __ Mouches, GK Destruktion, HGA 2 __ VK oder GK Blutung 3 __ NH Foramen und Makulaschichtforamen 4 __ ZVV oder VAV unilateral 5 __ Charles bonnet, Visuelle Halluzinationen 6  __ BH Pathologien 7 __ Uveitis anterior 8 __ HH Pathologien 9 __  Doppelbilder 10 __  Amotio rhetinae 11__ Endophthalmitis 12 __ AH Nävus 13 __  Erosio cornea 14__ IOL dezentriert 15__ Augenmigräne 16 __  Iritis, Iridocyclitis 17__ HKL subluxiert 18 ',
           'ocular_AE_unilateral_treatmentside       nicht betroffen 0_ bds 1 __  rechts 2 __     links 3 __   ',
           'ocular_AE_unilateral_medication              nicht betroffen 0_ bei Lucentis 1 __      bei Eylea 2 __       bei Luc & Eylea 3',
           'ocular_AE_unilateral_time   Time nach IVI till Event      nicht betroffen 0__    innert 24h 1 __ 24h-1 Woche 2 __         innerhalb 1Monat 3 __  >1Monat 4 __  unbekannt 5',
           'systemic_AE_bilateral           (Adverse event/Serious adverse event) Freitext       keine 0               Tod 1 __ Hospitalisation Grund unbekannt 2 __  Hosp Sturzereignis, Fraktur 3 __ Hosp Elektive Eingriffe 4 __ Lagerungsbedingte Beschwerden, RückenSz 5 __ CVI 6__ Onkolog. Path. 7 __ Hosp Stoffwechselerkrankungen, Infektionen, Dialyse, Fieber 8 __ Hosp Lungenentz, akute Dyspnoe. 9__ Synkope 10__ Schwindel, Kopfschmerzen, transiente Sehstörungen, Parästhesien 11__ Herzinfarkt 12 __ TVT 13__ Hosp Psychiatrisch 14__  Facialisparese 15__ Lungenembolie 16 __  Dermatologische Probleme, Haarausfall  17 __ Herzrhythmusstörungen, Herzrasen, VHFli, Kreislaufbeschwerden 18  __ Appendizitis 19 __ Rheumatologische Pathologie 20 __ Hosp Mediüberdosierung 21 __ Epileptischer Anfall 22',
           'systemic_AE_bilateral_medication     nicht betroffen 0_ bei Lucentis 1 __      bei Eylea 2 __       bei Luc & Eylea 3',
           'systemic_AE_bilateral_time         Time nach IVI till Event     nicht betroffen 0__     innert 24h 1 __ 24h-1 Woche 2 __         innerhalb 1Monat 3 __  >1Monat 4 __  unbekannt 5',
           'systemic_AE_unilateral         (Adverse event/Serious adverse event) Freitext keine 0               Tod 1 __ Hospitalisation Grund unbekannt 2 __  Hosp Sturzereignis, Fraktur 3 __ Hosp Elektive Eingriffe 4 __ Lagerungsbedingte Beschwerden, RückenSz 5 __ CVI 6__ Onkolog. Path. 7 __ Hosp Stoffwechselerkrankungen, Infektionen, Gürtelrose 8 __ Hosp Lungenentz.Dyspnoe 9__ Synkope  10__ Schwindel, Kopfschmerzen, transiente Sehstörungen, Paresen 11__ Herzinfarkt 12 __ TVT, Thrombosen  13__ Hosp Psychiatrisch 14__  Facialisparese 15__ Lungenembolie 16__ Hosp Dermatologisch  17__  Herzrhythmusstörungen, VhFli, Herzprobleme 18 __ GI-Pathologien, Appendizitis 19 __ Rheumatologische Pathologie 20 __ Hosp Mediüberdosierung 21 __ Epileptischer Anfall 22 __ Aneurysmaruptur 23 __ Epistaxis 24',
           'systemic_AE_unilateral_medication      nicht betroffen  0 _ bei Lucentis 1 __  bei Eylea 2 __      ',
           'systemic_AE_unilateral_time       Time nach IVI till Event      nicht betroffen 0__    innert 24h 1 __ 24h-1 Woche 2 __         innerhalb 1Monat 3 __  >1Monat 4 __  unbekannt 5',
           'Bemerkungen',
           'n_months_observationperiod   Beobachtungszeitraum T&E in Anz Monate',
           'n_months_T&E_PRN    Anzahl Mt im T&E+PRN Modus',
           'PRN_Eye_endline          PRN Auge Ende Beobachtungszeitraum       keines 0__ bds 1_ rechts 2_ links 3',
           'PRN_Eye_most_time                     PRN Auge meiste Zeit während Beobachtungszeitraum       keines 0_ rechts 2_ links 3',
           'n_months_bilateral_T&E              Anzahl Mt unter bilateraler T&E',
           'n_bilateral_T&E  Anzahl bilaterale T&E Injektionen',
           'n_bilateral T&E_PRN       Anzahl bilaterale T&E  +PRN Injektionen',
           'Startmodus_treatment              Beginn Beobachtungszeitraum bilat T&E 1__ T&E+PRN 2__ unilat T&E 3',
           'bilateral_T&E_pathway                         1. bilaterale T&E: Im Verlauf Wechsel auf                                nicht betroffen 1__   T&E+PRN 2 __  Exit T&E 3__Ozurdex bds 4__unilat T&E 5',
           'bilateral_T&E_to_PRN_cause  bilaterale T&E auf T&E+PRN: Begründung:          nicht betroffen 1__    Rez. Am PRN Auge > 12-14 Wo 2__ weniger Aktivität am PRN Auge, bei kurzen Intervallen am T&E Auge 3__ Flüssigkeit am PRN Auge toleriert  da nicht Visusrelevant 4__ Flüssigkeit am PRN Auge toleriert wegen red Visuspotential 5__ Auf Pat Wunsch 6__  St. n. CVI  7',
           'unilateral_pathway  3. unilat T&E: im Verlauf Wechsel auf                            nicht betroffen 1_  bilat T&E 2__ T&E+PRN 3__   ',
           'PRN_pathway        2.  T&E+PRN: Im Verlauf Wechsel auf: nicht betroffen 1__  bilat T&E  2__ unilat T&E  (PRN stopp) 3__ unverändert T&E+PRN 4__ Exit T&E 5',
           'PRN_T&E_cause   T&E+PRN beibehalten:        nicht betroffen 1__ Flüssigkeit toleriert an PRN Auge wegen schlechtem Visus 2__ Rezidive am PRN Auge >12-14 Wo 3__ Flüssigkeit am PRN Auge toleriert da nicht Visusrelevant 4__ ergibt sich aus unterschiedlicher Krankheitsaktivität 5__ aWdP 6__ Flüssigkeit toleriert an PRN Auge da stabil 7',
           'PRN_T&E_to_bilateral_T&E_cause   T&E+PRN: Grund für Wechsel auf T&E bds: nicht betroffen 1__ Rezidive am PRN Auge <12-14 Wo 2 __ Visus PRN Auge gut 3 __ beides 4',
           'Coordination_beginning_bilateral_T&E     Synchronisierung zu Beginn bilat T&E                                                            nicht erfolgt 1 __                                           Beginn synchronisiert unterschiedl Intervall 2__ Synchronisiert in gleichem Intervall 3',
           'Coordination_same_Intervall              Mehrheit der Anz bilat Injektionen: Synchronisierung in gleichen Intervallen               ja 1__ nein 2',
           'Coordination_different_Intervall    Mehrheit der Anz bilat Injektionen: Synchronisierung in unterschiedlichen Intervallen                     ja 1__ nein 2',
           'Coordination_base Synchronisierungsbasis         ergibt sich aus unterschiedl. Erkrankungsaktivität 1__ bei besserem Auge Abstand verkürzt zu Gunsten der Synchronisierung 2__ Flüssigkeit toleriert am schlechteren Auge zu Gunsten synchronisierung 3__ Gleiche Krankheitsaktivität bds 4 __keine Synchronisierung 5',
           'Coordination_cause         falls 2 oder 3 Begründung für Synchronisierung:               nicht betroffen 0 __ Situation am besseren Auge nicht stabil/vorgängig Rezidive unter längeren Intervallen 1 __ Schlechter AZ /aWdP / Malcompliance /bestmögliche Koordination R/L 2 __ Flüssigkeit toleriert am schlechteren Auge bei schlechter Visusprognose 3__ bei schlechter Visusprognose am besseren Auge anpassung an Intervall des schlechteren, besser sehenden Auges 4 __Exsudat stabil / sehr wenig Flüssigkeit regredient uner längeren Intervallen 5__ i.R. erster regulär 4 wöchentlicher T&E Intervalle 6',
           'no_coordination    keine Synchronisierung gefunden           nicht betroffen 0 __  ja 1__ nein 2',
           'no_coordination_cause                Wieso keine Synchronisierung gefunden?            Nicht betroffen 0 __ Intervallfindungsphase / unterschiedliche Krankheitsaktivität 1__ sehr unterschiedliche Behandlungsstadien (Behandlungsanfang vs. Ende) 2 __ aWdP /will keine bilateralen Injektionen / keine Koordination nötig bei langen Intervallen und niedriger Terminfrequenz 3__ St. n. CVI 4',
           'Malcompliance    Incompliant                  ja 1__ nein 2',
           'will keine bilateralen Injektionen                  ja 1__ nein 2',
           'Treatment_ending      Behandlungsabschluss T&E     Rezidivfrei nach 3x 14 Wo 1__ Behandlung läuft weiter 2__ Behandlung abgebrochen 3__        T&E Auge Rezidivfrei oder wechsel zu PRN, PRN Auge lohnt sich nicht mehr wegen schlechtem Visus 4__ Weiterführende Therapie mit Ozurdex 5',
           'Treatment_abortion_cause        Gründe für Behandlungsabbruch      nicht betroffen 1__     Arzt-/Klinikwechsel 2__ Krankheit/Hospitalisation oder Tod des Pat 3__  lost to follow-up 4__ Pat will keine IVI mehr 5__ Kein Therapieansprechen 6',
           'Bemerkung']

data = pd.read_excel("data_small.xlsx")
print(data)
data.hist("n_bilateral", bins=12)
plt.show()
print(data.columns)
# create new column
col1 = data.query("")
